{% set name = "spacy" %}
{% set version = "2.0.5" %}
{% set sha256sum = "4a47371b50232a1fa05f50cb83da4cc04a857dd0941e5d4f90fa8778e8c00e15" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Use-generic-optimizations.patch  # [linux]
    # Remove this when MKL 2018 update 2 is out.
    # xref: https://github.com/ContinuumIO/anaconda-issues/issues/8070
    - patches/0001-Add-workaround-for-MKL-bug-on-macOS.patch  # [osx]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - numpy

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28,<0.29
    - cymem >=1.30,<1.32.0
    - preshed >=1.0.0,<2.0.0
    - thinc >=6.10.1,<6.11.0
    - plac >=0.9.6,<1.0.0
    - six
    - pathlib  # [py2k]
    - ujson >=1.35
    - dill >=0.2,<0.3
    - requests >=2.13.0,<3.0.0
    - regex ==2017.4.5
    - ftfy >=4.4.2,<5.0.0
    - msgpack-numpy ==0.4.1
    - msgpack-python

test:
  requires:
    - pytest
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io/docs
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
