{% set name = "spacy" %}
{% set version = "3.8.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/explosion/spaCy/archive/refs/tags/release-v{{ version }}.tar.gz
  sha256: ad0ea4e15153de6703a1a77f22c34bdbf105b9362ccde4f4789e02dc9abcb538
  patches:
    - patches/0001-Ignore-deprecation-warnings-in-tests.patch # [py>=314]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - spacy = spacy.cli:setup_cli
  skip: True  # [py<39 or py>314]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0,<4.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - thinc >=8.3.12,<8.4.0
    - numpy {{ numpy }}
  run:
    - python
    - spacy-legacy >=3.0.11,<3.1.0
    - spacy-loggers >=1.0.0,<2.0.0
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc >=8.3.12,<8.4.0
    - wasabi >=0.9.1,<1.2.0
    - srsly >=2.5.3,<3.0.0
    - catalogue >=2.0.6,<2.1.0
    - weasel >=1.0.0,<2.0.0
    - confection >=1.3.2,<2.0.0
    - typer >=0.3.0,<1.0.0
    - tqdm >=4.38.0,<5.0.0
    - numpy >=1.15.0  # [py<39]
    - numpy >=1.19.0  # [py>=39]
    - requests >=2.13.0,<3.0.0
    - pydantic >=2.0.0,<3.0.0
    - jinja2
    - setuptools
    - packaging >=20.0
  run_constrained:
    # lookups
    - spacy_lookups_data >=1.0.3,<1.1.0
    # transformers
    - spacy-transformers >=1.1.2,<1.4.0
    #  cuda
    - cupy >=5.0.0b4,<13.0.0
    # cuda-autodetect
    - cupy-wheel>=11.0.0,<13.0.0
    # apple
    - thinc-apple-ops >=1.0.0,<2.0.0
    # Language tokenizers with external dependencies
    # ja
    - sudachipy >=0.5.2,!=0.6.1
    - sudachidict-core >=20211220
    # ko
    - natto-py >=0.9.0
    # th
    - pythainlp >=2.0

{% set deselect_tests = "" %}
# AssertionError: Registry 'loggers' missing entries: spacy.CupyLogger.v1, spacy.ChainLogger.v1, spacy.LookupLogger.v1, spacy.PyTorchLogger.v1, spacy.WandbLogger.v5, spacy.ClearMLLogger.v2, spacy.MLflowLogger.v2
# assert not {'spacy.ChainLogger.v1', 'spacy.ClearMLLogger.v2', 'spacy.CupyLogger.v1', 'spacy.LookupLogger.v1', 'spacy.MLflowLogger.v2', 'spacy.PyTorchLogger.v1', ...}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_registry_population.py::test_registry_entries" %}
# AssertionError: confection has different version in setup.cfg and in requirements.txt
{% set deselect_tests = deselect_tests + " --deselect=tests/package/test_requirements.py::test_build_dependencies" %}

test:
  source_files:
    # for pytest markers
    - setup.cfg
  imports:
    - spacy
    - spacy.training.alignment_array
    - spacy.training.example
    - spacy.parts_of_speech
    - spacy.strings
    - spacy.lexeme
    - spacy.vocab
    - spacy.attrs
    - spacy.kb.candidate
    - spacy.kb.kb
    - spacy.kb.kb_in_memory
    - spacy.ml.parser_model
    - spacy.morphology
    - spacy.pipeline.dep_parser
    - spacy.pipeline._edit_tree_internals.edit_trees
    - spacy.pipeline.morphologizer
    - spacy.pipeline.multitask
    - spacy.pipeline.ner
    - spacy.pipeline.pipe
    - spacy.pipeline.trainable_pipe
    - spacy.pipeline.sentencizer
    - spacy.pipeline.senter
    - spacy.pipeline.tagger
    - spacy.pipeline.transition_parser
    - spacy.pipeline._parser_internals.arc_eager
    - spacy.pipeline._parser_internals.ner
    - spacy.pipeline._parser_internals.nonproj
    - spacy.pipeline._parser_internals._state
    - spacy.pipeline._parser_internals.stateclass
    - spacy.pipeline._parser_internals.transition_system
    - spacy.pipeline._parser_internals._beam_utils
    - spacy.tokenizer
    - spacy.training.align
    - spacy.training.gold_io
    - spacy.tokens.doc
    - spacy.tokens.span
    - spacy.tokens.token
    - spacy.tokens.span_group
    - spacy.tokens.graph
    - spacy.tokens.morphanalysis
    - spacy.tokens._retokenize
    - spacy.matcher.matcher
    - spacy.matcher.phrasematcher
    - spacy.matcher.dependencymatcher
    - spacy.symbols
    - spacy.vectors
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs spacy {{ deselect_tests }}
  requires:
    - pip
    - pytest >=5.2.0,!=7.1.0
    - pytest-timeout >=1.3.0,<2.0.0
    - hypothesis >=3.27.0,<7.0.0
    # mock is constrained to >=2.0.0,<3.0.0 in requirements.txt, but no such
    # versions available in main. Version 4.0.x works just fine.
    - mock

about:
  home: https://spacy.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing (NLP) in Python
  description: |
    spaCy is a library for advanced Natural Language Processing in Python and Cython. 
    It's built on the very latest research, and was designed from day one to be used in real products.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
    - python_build_tool_in_run
