{% set name = "spacy" %}
{% set version = "1.9.0" %}
{% set sha256sum = "89d5d62dca5fd58a8032ba9dcccc8666bafe21bac203abf32881ddf90179b0a6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: python setup.py install -q --single-version-externally-managed --record=record.txt
  features:
    - vc{{ vc }}   # [win]

requirements:
  host:
    - msinttypes  # [win and py27]
    - python
    - setuptools
    - numpy
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.26,<0.27
    - cymem >=1.30,<1.32.0
    - preshed >=1.0.0,<2.0.0
    - thinc >=6.5.0,<6.6.0
    - plac <1.0.0,>=0.9.6
    - pip >=9.0.0,<10.0.0
    - six
    - pathlib
    - ujson >=1.35
    - dill >=0.2,<0.3
    - requests >=2.13.0,<3.0.0
    - regex >=2017.4.1,<2017.12.1
    - ftfy >=4.4.2,<5.0.0

test:
  requires:
    - pytest
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io/docs
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
