{% set name = "spacy" %}
{% set version = "2.0.16" %}
{% set sha256sum = "41de9353994aa782deb66a14742219b205ecd59fe11290ce39c4b914d05e0fbe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script:
    # xref: https://github.com/explosion/spaCy/issues/1592#issuecomment-360889011
    - mv $SRC_DIR/include/numpy $SRC_DIR/include/numpy.bak                                             # [ppc64le]
    - ln -s $PREFIX/lib/python${PY_VER}/site-packages/numpy/core/include/numpy $SRC_DIR/include/numpy  # [ppc64le]
    - rm spacy/tests/regression/test_issue957.py       # [not win]
    - rm spacy/tests/regression/test_issue2626.py      # [not win]
    - del /q spacy\tests\regression\test_issue957.py   # [win]
    - del /q spacy\tests\regression\test_issue2626.py  # [win]
    - {{PYTHON}} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - numpy
    # setup.py constrains wheel via setup_requires
    - wheel >=0.32.0,<0.33.0

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - msgpack-numpy <0.4.4
    - murmurhash >=0.28,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=2.0.1,<2.1.0
    - thinc >=6.12.0,<6.13.0
    - plac >=0.9.6,<1.0.0
    - ujson >=1.35
    - dill >=0.2,<0.3
    - regex >=2018.01.10
    - requests >=2.13.0,<3.0.0
    - pathlib2  # [py2k]

test:
  requires:
    - pytest
    - pytest-timeout
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
