{% set name = "spacy" %}
{% set version = "2.0.11" %}
{% set sha256sum = "cddb06e7965222e4339eb59d2258db8dadab19ef8b0a1a44a2d33f94935ba421" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Use-generic-optimizations.patch  # [linux]
    # Remove this when MKL 2018 update 2 is out.
    # xref: https://github.com/ContinuumIO/anaconda-issues/issues/8070
    - patches/0001-Add-workaround-for-MKL-bug-on-macOS.patch  # [osx]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - numpy

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cymem >=1.30,<1.32.0
    - dill >=0.2,<0.3
    - ftfy >=4.4.2,<5.0.0
    - msgpack-numpy ==0.4.1
    - msgpack-python
    - murmurhash >=0.28,<0.29
    - preshed >=1.0.0,<2.0.0
    - regex >=2017.4.5,<2017.12.1
    - requests >=2.13.0,<3.0.0
    - pathlib  # [py2k]
    - plac >=0.9.6,<1.0.0
    - six
    - thinc >=6.10.1,<6.11.0
    - ujson >=1.35

test:
  requires:
    - pytest
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
