{% set name = "spacy" %}
{% set version = "3.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b37ebd25ada4059b0dc9e0893e70dde5df83485329a068ef04580e70892a65d
  patches:
    - patches/0001-skip-beam-density-test.patch

build:
  number: 0
  # no s390x support
  # no python <3.9 support because of numpy >=2
  skip: True  # [py<39 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - spacy = spacy.cli:setup_cli

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - pip
    - python
    - numpy >=2.0.0,<2.1.0
    - setuptools
    - wheel
    - cython 3
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc >=8.3.0,<8.4.0
  run:
    - python
    # Spacy libraries
    - spacy-legacy >=3.0.11,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc >=8.3.0,<8.4.0
    - wasabi >=0.9.1,<1.2.0
    - srsly >=2.4.3,<3.0.0
    - catalogue >=2.0.6,<2.1.0
    - spacy-loggers >=1.0.0,<2.0.0
    - typer >=0.3.0,<0.10.0
    - weasel >=0.1.0,<0.5.0
    # Third-party dependencies
    - numpy >=2.0.0
    - tqdm >=4.,<3.038.0,<5.0.0
    - requests >=2.13.0,<3.0.0
    # Exclude pydantic 1.8.2 due to issues with python 3.11
    - pydantic >=1.7.4,!=1.8,!=1.8.1,!=1.8.2,<3.0.0
    - jinja2
    - langcodes >=3.2.0,<4.0.0
    # Official Python utilities
    - setuptools
    - packaging >=20.0
  run_constrained:
    - spacy-transformers >=1.1.2,<1.4.0

test:
  requires:
    - pip
    - pytest
    - pytest-timeout
    - mock
    - hypothesis
  imports:
    - spacy
  source_files:
    # for pytest markers
    - setup.cfg
  commands:
    - pip check
    # Skip test_find_available_port on osx-arm64 because of 'ValueError: [E1050] Port 5000 is already in use.'
    - python -m pytest --tb=native --pyargs {{ name }} -k "not test_find_available_port"  # [osx]
    - python -m pytest --tb=native --pyargs {{ name }}  # [not osx]

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing (NLP) in Python
  description: |
    spaCy is a library for advanced Natural Language Processing in Python and Cython. 
    It's built on the very latest research, and was designed from day one to be used in real products.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
    - python_build_tool_in_run
