{% set name = "spacy" %}
{% set version = "3.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e500cf2cb5f1849461a7928fa269703756069bdfb71559065240af6d0208b08c

build:
  number: 0
  # no s390x support due to cymem, preshed, thinc and pathy inavailability
  skip: True  # [py<36 or (linux and s390x)]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - spacy = spacy.cli:setup_cli

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cymem 2.0.6
    - cython 0.29.32
    - murmurhash 1.0.7
    - numpy {{ numpy }}
    - pathy 0.10.1
    - pip
    - preshed 3.0.6
    - setuptools
    - thinc 8.1.10
    - wheel
  run:
    - python
    # Spacy libraries
    - spacy-legacy >=3.0.10,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc >=8.1.0,<8.2.0
    - wasabi >=0.9.1,<1.1.0
    - srsly >=2.4.3,<3.0.0
    - catalogue >=2.0.6,<2.1.0
    - spacy-loggers >=1.0.0,<2.0.0
    # Exclude typer with unpinned click (>=0.3.2)
    - typer >=0.3.0,<0.8.0
    - pathy >=0.3.5
    # Third-party dependencies
    - tqdm >=4.38.0,<5.0.0
    - {{ pin_compatible('numpy') }}
    - requests >=2.13.0,<3.0.0
    # Exclude pydantic 1.8.2 due to issues with python 3.11
    - pydantic >=1.7.4,!=1.8,!=1.8.1,!=1.8.2,<1.11.0
    - jinja2
    - langcodes >=3.2.0,<4.0.0
    # Official Python utilities
    - setuptools
    - packaging >=20.0
    - typing_extensions >=3.7.4,<4.2.0  # [py<38]
    - smart_open >=5.2.1,<7.0.0

test:
  requires:
    - pip
    - pytest >=5.2.0,!=7.1.0
    - pytest-timeout >=1.3.0,<2.0.0
    - mock
    - hypothesis >=3.27.0,<7.0.0
  imports:
    - spacy
  commands:
    - pip check
    # Skip test_find_available_port on osx-arm64 because of 'ValueError: [E1050] Port 5000 is already in use.'
    - python -m pytest --tb=native --pyargs {{ name }} -k "not test_find_available_port"  # [osx and arm64]
    - python -m pytest --tb=native --pyargs {{ name }}  # [not (osx and arm64)]

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing (NLP) in Python
  description: |
    spaCy is a library for advanced Natural Language Processing in Python and Cython. 
    It's built on the very latest research, and was designed from day one to be used in real products.
  doc_url: https://spacy.io
  dev_url: https://github.com/explosion/spaCy

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
    - python_build_tool_in_run
