{% set name = "spacy" %}
{% set version = "2.0.12" %}
{% set sha256sum = "b220ebee412c19613c26b2c1870b60473834bd686cec49553ce5f184164d3359" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script:
    # xref: https://github.com/explosion/spaCy/issues/1592#issuecomment-360889011
    - mv $SRC_DIR/include/numpy $SRC_DIR/include/numpy.bak                                             # [ppc64le]
    - ln -s $PREFIX/lib/python${PY_VER}/site-packages/numpy/core/include/numpy $SRC_DIR/include/numpy  # [ppc64le]
    - rm spacy/tests/regression/test_issue957.py      # [not win]
    - del /q spacy\tests\regression\test_issue957.py  # [win]
    - {{PYTHON}} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - numpy

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28,<0.29
    - cymem >=1.30,<1.32.0
    - preshed >=1.0.0,<2.0.0
    - thinc >=6.10.3,<6.11.0
    - plac >=0.9.6,<1.0.0
    - six
    - pathlib2  # [py2k]
    - ujson >=1.35
    - dill >=0.2,<0.3
    - requests >=2.13.0,<3.0.0
    - regex >=2017.4.0,<=2018.7.11
    - msgpack-numpy >=0.4.1,<0.5.0
    - msgpack-python >=0.4.8,<0.5.7

test:
  requires:
    - pytest
    - pytest-timeout
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
