{% set name = "spacy" %}
{% set version = "2.3.1" %}
{% set sha256sum = "8f0dc4f7b995550302d233ebb723b5ddb343c7d24abe1276fc3488afef97c6bf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script:
    # xref: https://github.com/explosion/spaCy/issues/1592#issuecomment-360889011
    - mv $SRC_DIR/include/numpy $SRC_DIR/include/numpy.bak                                             # [ppc64le]
    - ln -s $PREFIX/lib/python${PY_VER}/site-packages/numpy/core/include/numpy $SRC_DIR/include/numpy  # [ppc64le]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - wheel
    - numpy 1.16.*
    - cython >=0.25
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - thinc ==7.4.1

  build:
    - {{ compiler('cxx') }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - thinc ==7.4.1
    - catalogue >=0.0.7,<1.1.0
    - plac >=0.9.6,<1.0.0
    - srsly >=1.0.2,<1.1.0
    - wasabi >=0.4.0,<1.1.0
    - jsonschema>=2.6.0,<3.1.0
    - requests >=2.13.0,<3.0.0
    - pathlib2 >=3.0.2,<3.1.0  # [py2k]
    - tqdm>=4.38.0,<5.0.0

test:
  requires:
    - pytest
    - mock
  imports:
    - spacy

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Industrial-strength Natural Language Processing
  description: |
    spaCy is a library for advanced natural language processing in Python and
    Cython.
  doc_url: https://spacy.io
  dev_url: https://github.com/spacy-io/spaCy

extra:
  recipe-maintainers:
    - rmax
    - ines
    - danielfrg
