travis:
  secure:
    BINSTAR_TOKEN: Kdt8ADd8RVbWLOzGdWG8A1VpjJhqL1IxxZ1BdtbgpHS6ywV6ZAfX01zeLbvokUslfe36TRAR3cFI1dqKx3zoP4+ehvszgaRCxdccGrkMHOo9Q7c9aIvO8oBbFK6NbpCnQdhBXMc4d6ABZGX1V51nDMBf3X/V+pLCXWM3OCMdzn3SwPFW1WZx4mWWphJV8vqEt2iKCMBEZcAdQ3yj4WzHTFx+c/N4jF8nC+tK0dR+2DtSPcMhDoCDMlGCXicvZnTMMzEiMSqWiRAHh7jGKCQ2pqw3X2DAtrk8t9pGMfwV3R1EuIFp2bzo2qGKZkvNttNHgWQa9XeBAXpd8JcqvYXLtI/Kd4PE5VYwebMLzEBWv3AMewmGjyWGw3aI3D0ahfbPd/i2xBgY6XBjV6d7DE5dBK4cDhJ5XqLNoX6EmpxQB67SGo4AoXp9i7A+rb/gKw4dz0DrOq0nnu6AbTecqNS1y9lwBn5/FL0xKR9arhw7FzAAOnkp4QQrOCNrWREENBqDVuGnnEnD9YqdPtcUD3YDDpHmWj0myZv2uQswymZmkzZ6GLFkmy4M89YdsPfGvMYF5qAoWT8IaeWHqPq5ZUu11vS0lru52ddA3faEdfEdcqvnt9MT8HdIX/TcxukU6W4SWzDXRvwYAvjs2Uic+obIRNu3rP9vqQDM/mblwY2Sl1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
